import Layout from "@/components/Layout";
export const metadata = {
  title: 'Code',
  description: 'Generated by create next app',
}

export default function CodeLayout({ children }) {
  return <Layout>{children}</Layout> 
}
