import Layout from "@/components/Layout";
export const metadata = {
    title: 'Dashboard',
    description: 'Generated by Aslam Zaman',
  }

 
  export default function ItemLayout({ children }) {
    return <Layout>{children}</Layout> 
  }

  